name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          swift package update
          swift build
          swift test